name: Build and Test bitfake2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            cmake \
            libtag1-dev \
            libfftw3-dev \
            libebur128-dev \
            libsndfile1-dev \
            libavformat-dev \
            libavcodec-dev \
            libavutil-dev \
            libswresample-dev

      - name: Build bitfake2
        run: |
          make install

      - name: Binary Check + help/versioning command.
        run: |
          bitf -v
          bitf -h
